---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-2.3.0
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install -g codeclimate-test-reporter
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test

addons:
  code_climate:
    repo_token: 145edba82f0f85ef8c28cd8d6a4ca4eb2cc8f2f7c002d2d76fbb62ab2a8b2712

after_script:
  - codeclimate-test-reporter < lcov.info
  - cat lcov.info | node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
